version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - VERSION=$(grep "projectVersion" gradle.properties | awk -F'=' '{print $2}' | tr -d ' ')
  build:
    commands:
      - echo Build started on `date`
      - echo "Project Version -> $VERSION"
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --s3-bucket dragan-nikolic-bucket1 --template-file template.yaml --output-template-file outputTemplate.yml
      - ls -la build/libs
artifacts:
  files:
    - build/libs/dragan-nikolic-$VERSION.jar
    - outputSamTemplate.yml
